### ISSUE TITLE
能不能增加一个功能：把选定的词加入用户词频词库

### ISSUE THREAD

**Issue by QiangF** [merrickluo/liberime#13]
非常怀念pyim的 数字＋v 加词，如果加入固态 dict.yaml 词库文件，实现简单，就需要 deploy 一下，所以希望有个不上屏加词的功能。

**Comment by tumashu** [comment]
pyim 已经支持了这种模式，不过仅仅用于 rime 全拼输入法，其他输入法由于无法获取一个词条的 code，搞不定

**Comment by QiangF** [comment]
感觉pyim这种添加方法有点绕，直接加到custom_phrase.txt然后重新deploy好像也挺快的。
由于qt5和一些软件支持不好，现在不用EXWM了，emacs里面单独一个输入法就u不是特别必要了。
fcitx.el 用起来还行。找到一些exwm功能的替代： rofi emacs-anywhere xkeysnail jumpapp greenclip linopen
