### ISSUE TITLE
能否提供一下对 windows 的支持

### ISSUE THREAD

**Issue by loyalpartner** [merrickluo/liberime#2]
你好，在 linux 里面用 pyim + rime 真的很方便，能不能对 windows 也支持一下呢

**Comment by merrickluo** [comment]
Windows 的工具链用得比较少不是很熟悉，如果有人帮忙最好了，没有的话我会抽时间研究下。

**Comment by tumashu** [comment]
window下面的话，可能基于 msys2 应该是最简单的， 不过 msys2 最大的问题是不包含 librime，

**Comment by merrickluo** [comment]
#26 @loyalpartner 有空可以试试

**Comment by loyalpartner** [comment]
收到

**Comment by tumashu** [comment]
此功能已经添加，见文档
