### ISSUE TITLE
MacOS 下更新到最新版后编译出错

### ISSUE THREAD

**Issue by cnsunyour** [merrickluo/liberime#28]
MacOS 10.15.3 ，git pull 到最新版，编译出错，错误信息如下：
```
[ 25%] Linking C shared library liberime.so
Undefined symbols for architecture x86_64:
  "_rime_get_api", referenced from:
      _liberime_init in liberime.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
尝试回退到
[ec4af812454d956a191870657828dd0769c9d3ae](https://github.com/merrickluo/liberime/commit/ec4af812454d956a191870657828dd0769c9d3ae)
后正常

**Comment by chuxubank** [comment]
+1

**Comment by shuxiao9058** [comment]
我的没问题啊

**Comment by chuxubank** [comment]
我使用的 doom-emacs, [配置文件](https://github.com/chuxubank/.doom.d/tree/master/modules/input/chinese%2B)
现在 pin 在了 [ec4af81245](https://github.com/merrickluo/liberime/commit/ec4af812454d956a191870657828dd0769c9d3ae) 这个 commit
使用最新的话就和 @cnsunyour 报一样的错

- macOS 10.15.3
- Doom v2.0.9 (Emacs v26.3)
- GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4) of 2019-12-04

**Comment by shuxiao9058** [comment]
我用的是[emacs-rime](https://github.com/DogLooksGood/emacs-rime)，没有问题 ~

**Comment by cnsunyour** [comment]
> 我使用的 doom-emacs, [配置文件](https://github.com/chuxubank/.doom.d/tree/master/modules/input/chinese%2B)
> 现在 pin 在了 [ec4af81245](https://github.com/merrickluo/liberime/commit/ec4af812454d956a191870657828dd0769c9d3ae) 这个 commit
> 使用最新的话就和 @cnsunyour 报一样的错
> 
> * macOS 10.15.3
> * Doom v2.0.9 (Emacs v26.3)
> * GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4) of 2019-12-04

好奇怪，我的 doom 怎么用 :pin 不生效呢？和你的配置一样啊

**Comment by chuxubank** [comment]
@cnsunyour 声明的 package 的名字必须是 `liberime` 而不是 `liberime-config` 我也是最近才发现这个问题...

**Comment by cnsunyour** [comment]
哦哦，非常感谢。这事困扰我一天了

**Comment by merrickluo** [comment]
简单看了下应该是添加 windows 支持对 CMakeLists.txt 的修改引起的，我研究下。

**Comment by chuxubank** [comment]
昨天测试了这个 fix 没有成功, 突然想到我是直接拿 squirrel 的 `librime.1.dylib` 放到 `$RIME_PATH/build/lib/Release/librime.dylib` 里的, 估计官方更新了API? 今天更新了squirrel 后也更新了`librime.1.dylib`(吐槽一下 brew cask 的脚本作者, 啥都auto_update) 终于成功. 感谢

**Comment by merrickluo** [comment]
> 突然想到我是直接拿 squirrel 的 librime.1.dylib 放到 $RIME_PATH/build/lib/Release/librime.dylib 

机智...我当时被boost版本折磨的时候怎么没想到这个办法（

理论上报错这个方法是api的主入口应该不会有改动才对，不过更新有用就好...
