### ISSUE TITLE
对 liberime 结构的一些思考

### ISSUE THREAD

**Issue by tumashu** [merrickluo/liberime#33]
1. 将 liberime.so 更改为 liberime-core.so,  只有速度要求高，或者只能通过c编写的接口才在这里实现。
2. 将 liberime-config.el 更改为 liberime.el， 速度要求不高的接口和接口辅助管理工具，在这个地方实现。

@merrickluo 你觉得怎么样。

**Comment by tumashu** [comment]
或者是 liberime-core liberime liberime-config 三层

**Comment by merrickluo** [comment]
听起来感觉不错，当初写liberime-config也是因为很多东西在C里面写起来很麻烦，如果pyim/emacs-rime能够把一些配置的wrapper拿过去其实config也没有存在的必要了。

**Comment by tumashu** [comment]
liberime-config 暂时不删除了， 以后也许有用， 另外也方便兼容
