### ISSUE TITLE
liberime更新后pyim无法使用

### ISSUE THREAD

**Issue by akikaede6** [merrickluo/liberime#45]
今天更新了liberime，为4c3032fd54decb995483a8015cb88f926c256520版本，使用的是doom， 但是在sandbox下测试了一下，vanilla Emacs也是用不了的。config.el为
```
;(use-package! liberime-config
; :init
; (add-hook 'liberime-after-start-hook
;            (lambda ()
;              (liberime-select-schema "luna_pinyin_simp")))
;  )

(use-package! pyim
  :after liberime-config
  :config
  (require 'liberime)
  (setq default-input-method "pyim")
  (setq pyim-default-scheme 'rime)
  (setq pyim-page-length 9)
  (setq pyim-page-tooltip 'posframe)
) 
```
packages.el
```
(package! liberime-config
  :recipe
  (
   :host github
   :repo "merrickluo/liberime"
   :files ("CMakeLists.txt" "Makefile" "src" "*.el")))
```
注释掉liberime的情况下，pyim可以正常使用，加上liberime的配置以后，c-\后灵通的标
志可以出现，但是不能输入中文，liberime也make过了,不知是哪里有问题?

**Comment by tumashu** [comment]
liberime-search “nihao”  有什么输出？

**Comment by merrickluo** [comment]
我这边也是用doom + master pyim + master liberime没有问题呢，你的pyim是用的doom的 chinese layer 提供的么？

**Comment by akikaede6** [comment]
> 我这边也是用doom + master pyim + master liberime没有问题呢，你的pyim是用的doom的 chinese layer 提供的么？

pyim用的是这个
```
(package! pyim
  :recipe
  (
   :host github
   :repo "merrickluo/pyim"))
```

**Comment by akikaede6** [comment]
> liberime-search “nihao” 有什么输出？

是在命令行吗?  是command not found,doom里M-x没有liberime-search

**Comment by tumashu** [comment]
(liberime-search “nihao”)

**Comment by akikaede6** [comment]
> (liberime-search “nihao”)

```
Debugger entered--Lisp error: (void-variable “nihao”)
  (liberime-search “nihao”)
  (progn (liberime-search “nihao”))
  eval((progn (liberime-search “nihao”)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  eros-eval-last-sexp(nil)
  funcall-interactively(eros-eval-last-sexp nil)
  call-interactively(eros-eval-last-sexp nil nil)
  command-execute(eros-eval-last-sexp)
```

**Comment by tumashu** [comment]
```
(liberime-search "nihao")
```

注意标点

**Comment by akikaede6** [comment]
> ```
> (liberime-search "nihao")
> ```
> 
> 注意标点

有中文输出,但是<kbd>c-\</kbd>还是没有输出

**Comment by tumashu** [comment]
pyim升级没？

**Comment by akikaede6** [comment]
> pyim升级没？

doom upgrade的时候
```
(29/187) Updating pyim...                                                       
      fatal: ambiguous argument 'bbeb68605e': unknown revision or path not in the working tree.                                                                         
      Use '--' to separate paths from revisions, like this:                         
      'git <command> [<revision>...] -- [<file>...]'  
```

**Comment by tumashu** [comment]
看起来像doom的问题，这个我没法帮你，我不了解doom

**Comment by shuxiao9058** [comment]
> > pyim升级没？
> 
> doom upgrade的时候
> 
> ```
> (29/187) Updating pyim...                                                       
>       fatal: ambiguous argument 'bbeb68605e': unknown revision or path not in the working tree.                                                                         
>       Use '--' to separate paths from revisions, like this:                         
>       'git <command> [<revision>...] -- [<file>...]'  
> ```

是不是版本写错了。。。

**Comment by merrickluo** [comment]
> > 我这边也是用doom + master pyim + master liberime没有问题呢，你的pyim是用的doom的 chinese layer 提供的么？
> 
> pyim用的是这个
> 
> ```
> (package! pyim
>   :recipe
>   (
>    :host github
>    :repo "merrickluo/pyim"))
> ```
repo写错了吧...我的fork很旧了

**Comment by tumashu** [comment]
汗， 试试 tumashu/pyim

**Comment by tumashu** [comment]
@merrickluo 别忘记设置一下 travis-ci ，这个我这边设置不了。 https://github.com/merrickluo/liberime/pull/47
