### ISSUE TITLE
能否和客户端共用一套配置文件

### ISSUE THREAD

**Issue by smartepsh** [merrickluo/liberime#8]
### 目标

想利用同一套配置文件，使系统下的输入法及在 emacs 中使用输入法，行为方式保持一致。

### 理由

配置目录下，包含各种输入方案的用户数据库文件，比如 `luna_pinyin.userdb` 。这个应该会根据输入记录（比如词频）来提升用户体验，但是现有情况下，无法在系统及 emacs 使用同一套配置路径，所以两边的用户体验可能不一致。

### 差异举例

`pyim` 一次性会根据配置一次性读取大量候选词，然后在自身中进行分页显示及选择；但是系统中，个人能接受的最大候选词数为 9 个（1-9）。

也就是说，`menu/page_size` 这个选项在两侧的配置是不一样的。

### 幻想

能否单独对 `liberime` 创建配置文件，而不影响系统中的输入法设置，仅为 pyim 服务？

**Comment by smartepsh** [comment]
先用文件软链接暂时作了同步。。

**Comment by merrickluo** [comment]
默认情况下liberime使用的配置路径是 `~/.emacs.d/rime`应该是不跟鼠须管或者fctix冲突的吧？另外两个librime instance同时共享一个配置路径的话会有问题，比如 `luna_pinyin.userdb` 是只能有一个instance能写入的，关于词库同步的问题，我正在 https://github.com/merrickluo/liberime/tree/feat-config 这个分支测试，应该很快会merge（

**Comment by smartepsh** [comment]
1. 是的，不会冲突。提这个问题的初衷，是我想偷懒直接把 liberime 的配置路径直接使用系统里的，比如 `~/Library/Rime/` ，就可以保证系统输入法和 pyim 完全行为一致了。
2. 同上，看起来是不行了。
3. 词库同步 👍 

这个东东真是解决了一个大痛点！之前在 emacs 用 evil 搞中文简直痛苦死了。。。
