### ISSUE TITLE
src/liberime.c:6:22: fatal error: rime_api.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by Iorest** [merrickluo/liberime#9]
src/liberime.c:6:22: fatal error: rime_api.h: 没有那个文件或目录

然后，安装librime-dev后，会有“unknown type name ‘RimeCandidateListIterator’”等错误

**Comment by merrickluo** [comment]
有具体的librime版本吗？

**Comment by Iorest** [comment]
安装的librime-dev ，具体版本是1.2.9+dfsg1-1

**Comment by merrickluo** [comment]
可能有点旧了，目前已知的最低版本要求是1.3.2 https://github.com/merrickluo/liberime/blob/cfd3fc2120c4d622b672152368651630727b55ee/README.org#L11
